[localnet]
# number of nodes in the single cluster of the localnet
nodes = 2
# number of seconds to wait for the localnet to come online
# Increased to 120 seconds to accommodate ARM64 emulation delays
localnet_timeout_secs = 120
